plugin:
    name: vojtasvoboda.usersidemenu::lang.plugin.name
    description: vojtasvoboda.usersidemenu::lang.plugin.description
    author: 'Vojta Svoboda'
    icon: icon-user
    homepage: 'https://github.com/vojtasvoboda/oc-usersidemenu-plugin'
